<?php
/**
 * Get the absolute path of project root folder
 * 
 * This function depends on where this file exists
 * Current it exists one level into the application
 * i.e. in rootFolder/src/thisfile.php
 * 
 * @return string Root path of the project folder
 */
function projectRoot() : string {
    return dirname(__DIR__, 1);
}

/**
 * Generate breadcrumb html markup
 * 
 * @param array $breadcrumbArray 
 * Expects an associative array that contains breadcrumb item name
 * as key and its url as value. The url should be relative. The 
 * absolute path will be generated by this function. The elements
 * in the array should be in the order of user progression of 
 * the menus.
 * 
 * @param string $activeItem
 * The currently active breadcrumb item. Used to provide additional
 * markup. The $activeItem should be equal to some item key in the
 * $breadcrumbArray
 */
function breadcrumbs(array $breadcrumbArray=[], string $activeItem='') {
    $breadcrumbs = $breadcrumbArray;
    $active = $activeItem;
    $separator = '&raquo;';
    $breadcrumbString = '';
    $c = count($breadcrumbs);
    foreach ($breadcrumbs as $item => $url) {
        $absPath = url_for($url);
        $activeClass = '';
        if (strtolower($active) === strtolower($item)) {
            $absPath = '#';
            $activeClass = 'style="border-bottom: 1px solid #005999; padding-bottom: 3px;"';
        }
        $breadcrumbString .= "<a href=\"{$absPath}\" {$activeClass}>{$item}</a>";
        $breadcrumbString .= ($c > 1) ? ' ' . $separator . ' ' : '';
        $c -= 1;
    }
    return $breadcrumbString;
}

function url_for($script_path)
{
    // adds the leading '/' if not present
    // (var_dump($script_path));
    if ($script_path === '#') {
        return '#';
    }
    if ($script_path == '' || $script_path[0] != '/')
    {
        $script_path = "/" . $script_path;
    }
    return WWW_ROOT . $script_path;
}

/**
 * Remove trailing slashes and trailing word 'index' from a string
 * 
 *  * '/index' returns '/'
 *  * '/customer/ returns '/customer'
 *  * '/customer/index/ returns /customer
 * 
 * @return string path
 */
function formatPath(string $path) :string {
    /* TODO Limit the lenght */

    // if path length is 1 then most likely path === '/' only
    // and contains a trailing slash
    if (strlen($path) > 1 && substr($path, -1) === '/') {
       $path = substr($path, 0, -1); // remove trailing slash
    }

    // check and remove words index from path
    if (substr($path, -5) === 'index') {
        $path = substr($path, 0, -5);
    }

    // if last 5 characters === 'index' OR has a trailing slash AND is greater than a single character run this function again.
    if ((substr($path, -5) === 'index' || substr($path, -1) === '/') && strlen($path) > 1) {
        return formatPath($path);
    }

    return $path;
}
?>
