<?php
define("WWW_ROOT", "/sbwms/public");
define("PUBLIC_PATH", getProjectPath() . '/public');
define("COMMON_VIEWS", getProjectPath() . '/resources/views/common/');
require_once(__DIR__ . '/../vendor/autoload.php');

/**
 * Get the project path.
 * 
 * The project directory must be name 'sbwms'
 * NOTE: The full path must contain forward slashes /
 */
function getProjectPath() : string {
    $currentPath = __DIR__;
    $directoryArray = explode(DIRECTORY_SEPARATOR, $currentPath);
    $position = array_search("sbwms", $directoryArray);
    if (!$position) exit("Please rename project folder to sbwms");
    $newarray = array_slice($directoryArray, 0, $position + 1);
    $projectPath = implode("/", $newarray);
    return $projectPath;
}
/**
 * Generate breadcrumb html markup
 * 
 * @param array $breadcrumbArray 
 * Expects an associative array that contains breadcrumb item name
 * as key and its url as value. The url should be relative. The 
 * absolute path will be generated by this function. The elements
 * in the array should be in the order of user progression of 
 * the menus.
 * 
 * @param string $activeItem
 * The currently active breadcrumb item. Used to provide additional
 * markup. The $activeItem should be equal to some item key in the
 * $breadcrumbArray
 */
function breadcrumbs(array $breadcrumbArray=[], string $activeItem='') {
    $breadcrumbs = $breadcrumbArray;
    $active = $activeItem;
    $separator = '&raquo;';
    $breadcrumbString = '';
    $c = count($breadcrumbs);
    foreach ($breadcrumbs as $item => $url) {
        $absPath = url_for($url);
        $activeClass = '';
        if (strtolower($active) === strtolower($item)) {
            $absPath = '#';
            $activeClass = 'style="text-decoration: underline;"';
        }
        $breadcrumbString .= "<a href=\"{$absPath}\" {$activeClass}>{$item}</a>";
        $breadcrumbString .= ($c > 1) ? ' ' . $separator . ' ' : '';
        $c -= 1;
    }
    return $breadcrumbString;
}

function url_for($script_path)
{
    // adds the leading '/' if not present
    // (var_dump($script_path));
    if ($script_path === '#') {
        return '#';
    }
    if ($script_path == '' || $script_path[0] != '/')
    {
        $script_path = "/" . $script_path;
    }
    return WWW_ROOT . $script_path;
}
?>
